INSERT INTO PRODUCT (NAME, DESCRIPTION) VALUES
    ('Egg', 'Egg'),
    ('Free Range & Organic Egg', 'Free Range & Organic Egg'),
    ('Fried Egg', 'Fried Egg'),
    ('Scrambled Eggs', 'Scrambled Eggs'),
    ('Boiled Egg', 'Boiled Egg'),
    ('Poached Egg', 'Poached Egg'),
    ('Scrambled Egg', 'Scrambled Egg'),
    ('Egg Salad, Egg', 'Egg Salad, Egg'),
    ('Eggs', 'Eggs'),
    ('Egg Salad, Egg', 'Egg Salad, Egg'),
    ('Egg Salad, Egg', 'Egg Salad, Egg'),
    ('Egg Beaters  Egg Product  Egg Whites', 'Egg Beaters  Egg Product  Egg Whites'),
    ('Bread, Egg', 'Bread, Egg'),
    ('Eggs', 'Eggs'),
    ('Eggs', 'Eggs'),
    ('Eggs', 'Eggs'),
    ('Eggs', 'Eggs'),
    ('Eggs', 'Eggs'),
    ('Eggs', 'Eggs'),
    ('Streit''s Egg Flakes Egg', 'Streit''s Egg Flakes Egg'),
    ('Eggs', 'Eggs'),
    ('Bread', 'Bread'),
    ('Wheat Bread', 'Wheat Bread'),
    ('Buttermilk Bread', 'Buttermilk Bread'),
    ('White Bread', 'White Bread'),
    ('Flax Bread', 'Flax Bread'),
    ('Sesame Bread', 'Sesame Bread'),
    ('Oat Bread', 'Oat Bread'),
    ('Multigrain Bread', 'Multigrain Bread'),
    ('White Wheat Bread', 'White Wheat Bread'),
    ('Honey Wheat Bread', 'Honey Wheat Bread'),
    ('Buckwheat Round Bread', 'Buckwheat Round Bread'),
    ('Bread Machine Bread', 'Bread Machine Bread'),
    ('Bread Stuffing, Bread, Dry Mix', 'Bread Stuffing, Bread, Dry Mix'),
    ('Bread Machine Sourdough Bread', 'Bread Machine Sourdough Bread'),
    ('Bread Machine White Bread', 'Bread Machine White Bread'),
    ('Italian Bread for the Bread MacHine', 'Italian Bread for the Bread MacHine'),
    ('Bread Machine Potato Bread', 'Bread Machine Potato Bread'),
    ('Bread Machine Wheat Bread', 'Bread Machine Wheat Bread'),
    ('Bread Machine French Bread', 'Bread Machine French Bread'),
    ('Bread Machine Garlic Bread', 'Bread Machine Garlic Bread'),
    ('Bread Machine Pumpernickel Bread', 'Bread Machine Pumpernickel Bread'),
    ('Bread, Rye', 'Bread, Rye'),
    ('Fish', 'Fish'),
    ('Fish Meat', 'Fish Meat'),
    ('Fish Filet', 'Fish Filet'),
    ('Drum Fish', 'Drum Fish'),
    ('Fish Liver', 'Fish Liver'),
    ('Pompano Fish', 'Pompano Fish'),
    ('Sucker Fish', 'Sucker Fish'),
    ('Hake Fish', 'Hake Fish'),
    ('Ara (Fish)', 'Ara (Fish)'),
    ('Steelhead Fish', 'Steelhead Fish'),
    ('Red Fish', 'Red Fish'),
    ('Basa Fish', 'Basa Fish'),
    ('Sable Fish', 'Sable Fish'),
    ('Fish', 'Fish'),
    ('Fish Seasoning, Fish', 'Fish Seasoning, Fish'),
    ('Fish, Fish Sticks, Frozen, Prepared', 'Fish, Fish Sticks, Frozen, Prepared'),
    ('Fish Broth', 'Fish Broth'),
    ('Fish, Surimi', 'Fish, Surimi'),
    ('Fish Sticks', 'Fish Sticks'),
    ('Fish Roe', 'Fish Roe'),
    ('Fish Sandwich', 'Fish Sandwich'),
    ('Fish Bouillon', 'Fish Bouillon'),
    ('Chicken', 'Chicken'),
    ('Fryer Chicken', 'Fryer Chicken'),
    ('Broiler Chicken', 'Broiler Chicken'),
    ('Chicken Drumstick', 'Chicken Drumstick'),
    ('Chicken Giblet', 'Chicken Giblet'),
    ('Chicken Heart', 'Chicken Heart'),
    ('Chicken Liver', 'Chicken Liver'),
    ('Chicken Neck', 'Chicken Neck'),
    ('Chicken, Roaster', 'Chicken, Roaster'),
    ('Chicken Drummette', 'Chicken Drummette'),
    ('Chicken Carcass', 'Chicken Carcass'),
    ('Chicken Breast', 'Chicken Breast'),
    ('Chicken Feet', 'Chicken Feet'),
    ('Chicken Gizzard', 'Chicken Gizzard'),
    ('Chicken Leg', 'Chicken Leg'),
    ('Chicken Meat', 'Chicken Meat'),
    ('Chicken Skin', 'Chicken Skin'),
    ('Chicken Thigh', 'Chicken Thigh'),
    ('Chicken Wing', 'Chicken Wing'),
    ('Chicken Mince', 'Chicken Mince'),
    ('Chicken Feet Boiled', 'Chicken Feet Boiled'),
    ('Chicken Drumstick Meat', 'Chicken Drumstick Meat'),
    ('Tofu', 'Tofu'),
    ('Water-Packed Tofu', 'Water-Packed Tofu'),
    ('Water-Packed Firm Tofu', 'Water-Packed Firm Tofu'),
    ('Firm Tofu', 'Firm Tofu'),
    ('Tofu', 'Tofu'),
    ('Tofu in Sunrice Sauce, Tofu', 'Tofu in Sunrice Sauce, Tofu'),
    ('Mabo Tofu', 'Mabo Tofu'),
    ('Tofu', 'Tofu'),
    ('Tofu', 'Tofu'),
    ('Tofu', 'Tofu'),
    ('Tofu, Fried', 'Tofu, Fried'),
    ('Egg Tofu', 'Egg Tofu'),
    ('Soft Tofu', 'Soft Tofu'),
    ('Tofu Feta', 'Tofu Feta'),
    ('Heiwa Tofu Organic Tofu', 'Heiwa Tofu Organic Tofu'),
    ('Tofu Bacon', 'Tofu Bacon'),
    ('Tofu Steak', 'Tofu Steak'),
    ('Tofu Cheesecake', 'Tofu Cheesecake'),
    ('Tofu Jerky', 'Tofu Jerky'),
    ('Tofu Lasagna', 'Tofu Lasagna'),
    ('Agedashi Tofu', 'Agedashi Tofu'),
    ('Balsamic Tofu', 'Balsamic Tofu');
